"""empty message

Revision ID: 6d936f8a524d
Revises: 54ab8412c3fb
Create Date: 2018-05-15 23:54:37.679956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d936f8a524d'
down_revision = '54ab8412c3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'id')
    op.drop_column('store_tags', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_tags', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.add_column('favorites', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    # ### end Alembic commands ###
