"""empty message

Revision ID: de98c08987d1
Revises: 6d936f8a524d
Create Date: 2018-06-03 18:20:26.461596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de98c08987d1'
down_revision = '6d936f8a524d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('stores', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('stores', sa.Column('telephone', sa.String(length=20), nullable=True))
    op.alter_column('stores', 'category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('stores', 'telephone')
    op.drop_column('stores', 'description')
    op.drop_column('reviews', 'score')
    # ### end Alembic commands ###
